# Generated by Django 2.2.20 on 2021-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaveExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('uuid', models.CharField(blank=True, default='', max_length=64, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'After Save Example',
                'verbose_name_plural': 'After Save Examples',
            },
        ),
    ]
