# Generated by Django 3.2.8 on 2021-10-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleFkModelForBaseAdminMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleM2MModelForBaseAdminMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModelForBaseAdminMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_boolean', models.BooleanField(null=True, verbose_name='Test bool')),
                ('test_datetime', models.DateTimeField(verbose_name='Test datetime')),
                ('test_image', models.ImageField(upload_to='example/images/', verbose_name='Test image')),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_for_base_admin_mixins', to='example.examplefkmodelforbaseadminmixin', verbose_name='Test fk')),
                ('test_m2m', models.ManyToManyField(related_name='example_for_base_admin_mixins', to='example.ExampleM2MModelForBaseAdminMixin')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleGenericRelationModelForBaseAdminMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
