# Generated by Django 3.2.8 on 2021-11-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaveExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
            ],
            options={
                'verbose_name': 'After save example model',
                'verbose_name_plural': 'After save example models',
            },
        ),
        migrations.CreateModel(
            name='BaseExampleFkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
            ],
            options={
                'verbose_name': 'Base example FK model',
                'verbose_name_plural': 'Base example FK models',
            },
        ),
        migrations.CreateModel(
            name='BaseExampleM2MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
            ],
            options={
                'verbose_name': 'Base example M2M model',
                'verbose_name_plural': 'Base example M2M models',
            },
        ),
        migrations.CreateModel(
            name='ConfigurableWidgetsExampleFKModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Test Text')),
            ],
            options={
                'verbose_name': 'Configurable widgets example FK model',
                'verbose_name_plural': 'Configurable widgets example FK models',
            },
        ),
        migrations.CreateModel(
            name='ConfigurableWidgetsExampleM2MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Test Text')),
            ],
            options={
                'verbose_name': 'Configurable widgets example M2M model',
                'verbose_name_plural': 'Configurable widgets example M2M models',
            },
        ),
        migrations.CreateModel(
            name='ExtraButtonExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(blank=True, default='', verbose_name='Test Text')),
            ],
            options={
                'verbose_name': 'Extra button example model',
                'verbose_name_plural': 'Extra button example models',
            },
        ),
        migrations.CreateModel(
            name='FloatingExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(max_length=255, verbose_name='Test Text')),
            ],
            options={
                'verbose_name': 'Floating example model',
                'verbose_name_plural': 'Floating example models',
            },
        ),
        migrations.CreateModel(
            name='ImprovedRawIdFieldsExampleRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Test Name')),
            ],
            options={
                'verbose_name': 'Improve raw id fields example related model',
                'verbose_name_plural': 'Improve raw id fields example related models',
            },
        ),
        migrations.CreateModel(
            name='ImprovedRawIdFieldsExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Test Name')),
                ('test_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_test_fk', related_query_name='related_test_fk', to='example.improvedrawidfieldsexamplerelatedmodel', verbose_name='Test FK')),
                ('test_m2m', models.ManyToManyField(related_name='related_test_m2m', related_query_name='related_test_m2m', to='example.ImprovedRawIdFieldsExampleRelatedModel', verbose_name='Test M2M')),
            ],
            options={
                'verbose_name': 'Improve raw id fields example model',
                'verbose_name_plural': 'Improve raw id fields example models',
            },
        ),
        migrations.CreateModel(
            name='EmptyValueExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(blank=True, default='', verbose_name='Test Text')),
                ('test_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='example.emptyvalueexamplemodel', verbose_name='Test FK')),
            ],
            options={
                'verbose_name': 'Empty value example model',
                'verbose_name_plural': 'Empty value example models',
            },
        ),
        migrations.CreateModel(
            name='DetailInInlineExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(blank=True, default='', verbose_name='Test Text')),
                ('test_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='example.detailininlineexamplemodel', verbose_name='Text FK')),
            ],
            options={
                'verbose_name': 'Detail in inline example model',
                'verbose_name_plural': 'Detail in inline example models',
            },
        ),
        migrations.CreateModel(
            name='ConfigurableWidgetsExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(blank=True, default='', max_length=500, verbose_name='Test Text')),
                ('test_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='example.configurablewidgetsexamplefkmodel', verbose_name='Test FK')),
                ('test_m2m', models.ManyToManyField(to='example.ConfigurableWidgetsExampleM2MModel', verbose_name='Test M2M')),
            ],
            options={
                'verbose_name': 'Configurable widgets example model',
                'verbose_name_plural': 'Configurable widgets example models',
            },
        ),
        migrations.CreateModel(
            name='BaseExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_boolean', models.BooleanField(null=True, verbose_name='Test bool')),
                ('test_datetime', models.DateTimeField(verbose_name='Test datetime')),
                ('test_image', models.ImageField(upload_to='example/images/', verbose_name='Test image')),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_for_base_admin_mixins', to='example.baseexamplefkmodel', verbose_name='Test fk')),
                ('test_m2m', models.ManyToManyField(related_name='example_for_base_admin_mixins', to='example.BaseExampleM2MModel')),
            ],
            options={
                'verbose_name': 'Base example model',
                'verbose_name_plural': 'Base example models',
            },
        ),
        migrations.CreateModel(
            name='BaseExampleGenericRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(verbose_name='Test text')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Base example generic relation model',
                'verbose_name_plural': 'Base example generic relation models',
            },
        ),
        migrations.CreateModel(
            name='AllReadonlyExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(blank=True, verbose_name='Test Text')),
                ('test_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='example.allreadonlyexamplemodel')),
            ],
            options={
                'verbose_name': 'All readonly example model',
                'verbose_name_plural': 'All readonly example models',
            },
        ),
    ]
