# Generated by Django 2.2.20 on 2021-04-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdminExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Datetime')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('boolean', models.BooleanField(default=False, verbose_name='Boolean')),
                ('after_save_fk_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='example.AfterSaveExample')),
                ('after_save_m2m_example', models.ManyToManyField(blank=True, related_name='base_admin', to='example.AfterSaveExample')),
            ],
            options={
                'verbose_name': 'Base Admin Example',
                'verbose_name_plural': 'Base Admin Examples',
            },
        ),
    ]
