# Generated by Django 2.2.20 on 2021-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_baseadminexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadminexample',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
