default_language_version:
    python: python3
fail_fast: true
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
      exclude: ^.*\b(migrations)\b.*$
    - id: flake8
      name: flake8
      entry: flake8
      exclude: main.py
      language: python
      types: [python]
    - id: isort
      name: isort
      entry: isort
      language: python
      types: [python]
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python runtests.py
        always_run: true
        verbose: true
        pass_filenames: false
        language: system